name: timeninja
description: A time tracking app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.7.0

dependencies:
  bloc: ^8.1.0
  drift: ^2.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  package_info_plus: ^3.0.3
  path: ^1.8.2
  path_provider: ^2.0.12
  provider: ^6.0.5
  shared_preferences: ^2.0.18
  sqlite3_flutter_libs: ^0.5.12

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.0
  drift_dev: ^2.5.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  generate: true
# dependency_overrides:
#   # Flutter's test packages don't support the latest analyzer yet.
#   test_api: ^0.4.16
